### ISSUE TITLE
Specify that it needs Python2 and not 3

### ISSUE THREAD

**Issue by Naereen** [fogleman/PirateMap#4]
Hi!
I love that project, it's really fun and neat! :skull_and_crossbones: :crossed_swords: !

Could you specify, both on the `main.py` shebang and on the `README.md` file, that the project runs on Python2 ?

Also, Pillow could be removed from the requirements (and the lines #39,40 of `layers.py` commented) as it is only needed for debugging.
(I failed to `pip install` the requirements on a `virtualenv` only because of a Pillow-related bug)

**Comment by GabLeRoux** [comment]
I had this error while trying to use Python 3.5.2:
```
❯ python main.py
  File "main.py", line 86
    end = max(points, key=lambda (x, y): layer.get(x, y))
                                 ^
SyntaxError: invalid syntax
```
Here's a PR for the readme.

Using a python2 virtualenv worked (still generating atm) :)

**Comment by Naereen** [comment]
Yep, Python 3 `lambda` functions can't have parentheses here. But this part is solved to be valid for both Python 2 and 3 with simply:
```python
    end = max(points, key=layer.get)
```
Here is a PR #7 fixing this point, and using `range` instead of `xrange` and `print(seed)` instead of `print seed` (if running on Python 3).

Now the only issue to check is the dependencies, not the code.

**Comment by Naereen** [comment]
Arf,  you did the same but better, in 0328f0a. Merge yours, not mine!
